# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 622eef4ee331994fd2a8051518c4e3c68fb16fac3ce660f70cbd290f09ea9c51c8b4233a7c5f8f0957251244d171928ffd89b6b3bda1f451fde2da4401ee4c07

test:
  secret_key_base: b0574cb4f6374e0572786bb62f66024a1967a0816905739e363254c3d1a65506322f13731f888b25c80dad7c4a58ff256ce61237abc00bf2eb62ff1d92770d78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
